### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x256 and 600x24)

### ISSUE THREAD

**Issue by yangpipi-01** [Guan-MS/WaterMamba#2]
2024-12-18 11:08:48,737 INFO: [Water..][epoch:  8, iter:   2,000, lr:(3.000e-04,)] [eta: 12:23:00, time (data): 0.147 (0.001)] l_pix: 4.4725e-02 
2024-12-18 11:08:48,737 INFO: Saving models and training states.
Traceback (most recent call last):
  File "/root/autodl-tmp/WaterMamba-main/basicsr/train.py", line 325, in <module>
    main()
  File "/root/autodl-tmp/WaterMamba-main/basicsr/train.py", line 299, in main
    model.validation(val_loader, current_iter, tb_logger,
  File "/root/autodl-tmp/WaterMamba-main/basicsr/models/base_model.py", line 51, in validation
    return self.nondist_validation(dataloader, current_iter, tb_logger,
  File "/root/autodl-tmp/WaterMamba-main/basicsr/models/image_restoration_model.py", line 237, in nondist_validation
    test()
  File "/root/autodl-tmp/WaterMamba-main/basicsr/models/image_restoration_model.py", line 184, in pad_test
    self.nonpad_test(img)
  File "/root/autodl-tmp/WaterMamba-main/basicsr/models/image_restoration_model.py", line 201, in nonpad_test
    pred = self.net_g(img)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/WaterMamba-main/basicsr/models/archs/WaterMamba_arch.py", line 696, in forward
    out_enc_level1 = self.encoder_level1(inp_enc_level1)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/WaterMamba-main/basicsr/models/archs/WaterMamba_arch.py", line 519, in forward
    x = ((input * self.skip_scale).permute(0, 3, 1, 2) + self.drop_path2(self.CCOSS(x))).permute(0, 2, 3, 1)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/WaterMamba-main/basicsr/models/archs/WaterMamba_arch.py", line 295, in forward
    x_h= self.H_CSSM(x_h).permute(0, 3, 2, 1)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/WaterMamba-main/basicsr/models/archs/WaterMamba_arch.py", line 160, in forward
    self.in_proj.weight @ rearrange(u, "b l d -> d (b l)"),
RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x256 and 600x24)

**Comment by Guan-MS** [comment]
请将图像裁剪为256*256












关美盛
***@***.***






---Original---
From: ***@***.***&gt;
Date: Wed, Dec 18, 2024 11:12 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Guan-MS/WaterMamba] RuntimeError: mat1 and mat2 shapes cannot bemultiplied (512x256 and 600x24) (Issue #2)




 
2024-12-18 11:08:48,737 INFO: [Water..][epoch:  8, iter:   2,000, lr:(3.000e-04,)] [eta: 12:23:00, time (data): 0.147 (0.001)] l_pix: 4.4725e-02
 2024-12-18 11:08:48,737 INFO: Saving models and training states.
 Traceback (most recent call last):
 File "/root/autodl-tmp/WaterMamba-main/basicsr/train.py", line 325, in 
 main()
 File "/root/autodl-tmp/WaterMamba-main/basicsr/train.py", line 299, in main
 model.validation(val_loader, current_iter, tb_logger,
 File "/root/autodl-tmp/WaterMamba-main/basicsr/models/base_model.py", line 51, in validation
 return self.nondist_validation(dataloader, current_iter, tb_logger,
 File "/root/autodl-tmp/WaterMamba-main/basicsr/models/image_restoration_model.py", line 237, in nondist_validation
 test()
 File "/root/autodl-tmp/WaterMamba-main/basicsr/models/image_restoration_model.py", line 184, in pad_test
 self.nonpad_test(img)
 File "/root/autodl-tmp/WaterMamba-main/basicsr/models/image_restoration_model.py", line 201, in nonpad_test
 pred = self.net_g(img)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
 return self._call_impl(*args, **kwargs)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
 return forward_call(*args, **kwargs)
 File "/root/autodl-tmp/WaterMamba-main/basicsr/models/archs/WaterMamba_arch.py", line 696, in forward
 out_enc_level1 = self.encoder_level1(inp_enc_level1)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
 return self._call_impl(*args, **kwargs)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
 return forward_call(*args, **kwargs)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
 input = module(input)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
 return self._call_impl(*args, **kwargs)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
 return forward_call(*args, **kwargs)
 File "/root/autodl-tmp/WaterMamba-main/basicsr/models/archs/WaterMamba_arch.py", line 519, in forward
 x = ((input * self.skip_scale).permute(0, 3, 1, 2) + self.drop_path2(self.CCOSS(x))).permute(0, 2, 3, 1)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
 return self._call_impl(*args, **kwargs)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
 return forward_call(*args, **kwargs)
 File "/root/autodl-tmp/WaterMamba-main/basicsr/models/archs/WaterMamba_arch.py", line 295, in forward
 x_h= self.H_CSSM(x_h).permute(0, 3, 2, 1)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
 return self._call_impl(*args, **kwargs)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
 return forward_call(*args, **kwargs)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
 input = module(input)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
 return self._call_impl(*args, **kwargs)
 File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
 return forward_call(*args, **kwargs)
 File "/root/autodl-tmp/WaterMamba-main/basicsr/models/archs/WaterMamba_arch.py", line 160, in forward
 self.in_proj.weight @ rearrange(u, "b l d -&gt; d (b l)"),
 RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x256 and 600x24)
